baseURL = "https://alkanani.dev/"
languageCode = "en-gb"
title = "David Al-Kanani Profile"
theme = ["github.com/eddiewebb/hugo-resume"]
publishDir = "docs"

[params]
    firstName = "David"
    lastName = "Al-Kanani"
    address = "London, UK"
    profileImage = "img/totoro.png"
    emailUser = "david.alkanani"
    emailHost = "gmail.com"
    description = "Profile for David Al-Kanani"
    favicon = "favicon.ico"

    showQr = false
    showContact = false
    showSocializations = true

    sections = ["skills", "experience", "education"]

    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true
    showCertifications = false
    showBoards = false

    gitCommitPrefix = "https://github.com/davidalk/profile/commit/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/davidalk/"

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/david-al-kanani-48aa73/"

[params.google.analytics]
    trackerID = ""

[outputs]
    home = ["HTML", "JSON"]